### PR TITLE
DM-40383-hotfix: Remove SConscript in doc folder

### PR DESCRIPTION
**Pull request by arunkannawadi**

### CODE REVIEW

**Comment by arunkannawadi** [comment]
Jenkins is running here: https://rubin-ci.slac.stanford.edu/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/250/pipeline

I could merge this PR once `cell_coadds` gets built.

**Comment by arunkannawadi** [comment]
@timj - `cell_coadds` build has passed.

**Review by timj — APPROVED** [review]
Sorry. Was dinner time here.

**Comment by arunkannawadi** [comment]
Oh, no worries at all! Thanks for noticing the breakage and suggesting the fix.

**Pull request merged**
